### ISSUE TITLE
Support Dockerfile format

### ISSUE THREAD

**Issue by nicosto** [instrumenta/conftest#8] opened 2019-06-07 04:11 UTC
Hi,
To expand the potential places where Conftest could be used, it would be good to support dockerfile as an input. 
Thanks

**Comment by garethr** [comment] 2019-06-29 18:11
conftest now has a parser interface (see https://github.com/instrumenta/conftest/pull/17) which should support this feature.

**Comment by nicosto** [comment] 2019-06-29 23:50
Thanks a lot, I'll take a look at this.

**Comment by Blokje5** [comment] 2019-07-26 16:05
I am working on this atm. Having some issues with the different dependencies on Docker (via the oras dependencies) and looking on a way to resolve it.

```
#11 123.9 go/pkg/mod/github.com/deislabs/oras@v0.5.1-0.20190510174428-2836a4314d4a/pkg/oras/pull_opts.go:22:3: cannot use images.Dispatch (type func(context.Context, images.Handler, *semaphore.Weighted, ...v1.Descriptor) error) as type func(context.Context, images.Handler, ...v1.Descriptor) error in field value
#11 123.9 go/pkg/mod/github.com/deislabs/oras@v0.5.1-0.20190510174428-2836a4314d4a/pkg/oras/push.go:46:69: cannot use opt.baseHandlers (type []images.Handler) as type func(images.Handler) images.Handler in argument to remotes.PushContent
#11 123.9 go/pkg/mod/github.com/deislabs/oras@v0.5.1-0.20190510174428-2836a4314d4a/pkg/oras/push.go:46:69: invalid use of ... in call to remotes.PushContent
#11 127.8 # github.com/deislabs/oras/pkg/auth/docker
#11 127.8 go/pkg/mod/github.com/deislabs/oras@v0.5.1-0.20190510174428-2836a4314d4a/pkg/auth/docker/login.go:26:3: unknown field 'V2Only' in struct literal of type "github.com/docker/docker/registry".ServiceOptions
------
executor failed running [/bin/sh -c GOOS=linux GOARCH=amd64 go build -o conftest -ldflags="-w -s" cmd/main.go]: exit code: 2
make: *** [conftest] Error 1
```

**Comment by jpreese** [comment] 2019-08-19 18:13
I want to put this here for visibility and.. because I'll inevietably forget everything I've found 🤙 

So asottile has updated his package to use buildkit, which is great
https://github.com/asottile/dockerfile/blob/master/parse.go

That lone import gets us pretty much all the way there. We just need to reference that package, call parse, and we're off to the races.

The problem is that buildkit depends on containerd v1.3.0-psuedo
https://github.com/moby/buildkit/blob/master/go.mod#L12

and oras depends on v1.2.6
https://github.com/deislabs/oras/blob/master/go.mod#L12

While this shouldnt be a problem, containerd made a _breaking_ change in v1.3.0 -- so when including buildkit into our project, it bumps up the containerd dependency which breaks oras.

Oras needs to include containerd v1.3.0, and then fix their library, because.. v1.3.0 breaks it. Or containerd needs to release a v2 (though they are not on modules)

**Comment by Blokje5** [comment] 2019-08-19 19:44
@jpreese I have a working version using replace in go mod to utilise `containerd v1.2.6`. Indeed it would be ideal if this is resolved in `containerd`, but in the mean time we can use replace. You can check out the PR if you want.

**Comment by jpreese** [comment] 2019-08-19 19:56
Let's see what happens with the issue on the containerd repository. I'd rather not duplicate the `parser.go` file from asottile's repository if we don't have to.

**Comment by garethr** [comment] 2019-08-19 20:00
@jdolitsky may be able to help with pointers on the Oras front as well.

**Comment by jdolitsky** [comment] 2019-08-19 21:10
oh my... these dependency issues again.

I've just opened https://github.com/deislabs/oras/issues/111 to update containerd dependency

**Comment by jdolitsky** [comment] 2019-08-26 00:05
PR opened for this https://github.com/deislabs/oras/pull/116

Will report back when we have a release ready for you to use

**Comment by jdolitsky** [comment] 2019-08-26 13:18
@jpreese @Blokje5 @garethr ORAS v0.7.0 has been released updating these dependencies. Please let me know if this solves the issue

https://github.com/deislabs/oras/releases/tag/v0.7.0

**Closed** 2019-09-01 14:59 UTC
Labels: enhancement
